Dream Cars/force-app/main/default/objects/Planned_Sales__c/Planned_Sales__c.object-meta.xml
<CustomObject>
    <label>Planned Sales</label>
    <nameField>
        <label>Planned Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Sales</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Dream Cars/force-app/main/default/objects/Planned_Sales__c/fields/Count_of_Cars_Sold__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Cars_Sold__c</fullName>
    <label>Count of Cars Sold</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Dream Cars/force-app/main/default/objects/Planned_Sales__c/fields/Total_Amount_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Earned__c</fullName>
    <label>Total Amount Earned</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Dream Cars/force-app/main/default/objects/Product2/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condition</valueSetName>
    </valueSet>
</CustomField>

Dream Cars/force-app/main/default/classes/PlannedSalesCalculationService.cls
public class PlannedSalesCalculationService {

    public static void getSalesData(List<Planned_Sales__c> plannedSalesList) {

        Set<Integer> years = new Set<Integer>();
        Set<Integer> months = new Set<Integer>();
        Set<String> carTypes = new Set<String>();

        for (Planned_Sales__c plannedSales : plannedSalesList) {
            years.add(plannedSales.Year__c);
            months.add(plannedSales.Month__c);
            carTypes.add(plannedSales.Car_Type__c);
        }

        List<AggregateResult> result = [SELECT 
                                        MONTH(Opportunity.CloseDate) mnth, 
                                        YEAR(Opportunity.CloseDate) yr, 
                                        Product2.Condition__c tp, 
                                        SUM(TotalPrice) totalAmount, 
                                        COUNT(Id) totalDeals 
                                  FROM OpportunityLineItem 
                                  WHERE Opportunity.StageName = 'Closed Won' 
                                  AND Product2.Condition__c IN :carTypes 
                                  AND YEAR(Opportunity.CloseDate) IN :years 
                                  AND MONTH(Opportunity.CloseDate) IN :months
                                  WITH USER_MODE
                                  GROUP BY YEAR(Opportunity.CloseDate), MONTH(Opportunity.CloseDate), Product2.Condition__c];

        Map<String, AggregateResult> resultDataMap = new Map<String, AggregateResult>();
        for (AggregateResult ar : result) {
            String key = String.valueOf((Integer)ar.get('yr')) + '-' + String.valueOf((Integer)ar.get('mnth')) + '-' + (String)ar.get('tp');
            resultDataMap.put(key, ar);
        }

        for (Planned_Sales__c ps : plannedSalesList) {
            String key = String.valueOf(ps.Year__c) + '-' + String.valueOf(ps.Month__c) + '-' + ps.Car_Type__c;
            if (resultDataMap.containsKey(key)) {
                AggregateResult ar = resultDataMap.get(key);
                ps.Total_Amount_Earned__c = (Decimal)ar.get('totalAmount');
                ps.Count_of_Cars_Sold__c = (Integer)ar.get('totalDeals');
            } else {
                ps.Total_Amount_Earned__c = 0;
                ps.Count_of_Cars_Sold__c = 0;
            }
        }
    }
}